### ISSUE TITLE
Latest version says to update

### ISSUE THREAD

**Issue by agamsol** [Lilwiggy/counter-strike-rpc#7]
i installed the latest version and it prompts that there is other update

**Comment by Lilwiggy** [comment]
I’m very sorry I didn’t see this sooner! I am aware of this issue but time has just been away from me and I am out of town for a while now due to a family emergency. It is a very easy fix and I will get it fixed ASAP. Apologies for the delayed response

**Comment by Lilwiggy** [comment]
Fixed in #8 :)
